# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  azCliVersion: 2.6.0
  ref_javaee: 6addd99d8bc3f472e040f11c053a37e1ac370229
  offerName: azure.websphere-traditional.image
  userEmail: ${{ secrets.USER_EMAIL }}
  userName: ${{ secrets.USER_NAME }}
  ibmUserId: ${{ secrets.IBM_USER_ID }}
  ibmPassword: ${{ secrets.IBM_PASSWORD }}
  vmAdminId: websphere
  vmAdminPassword: Secret123456
  storagteResourceGroup: zheng-test-rg
  storageAccountName: stagevhekpiwmxfyjjqoocjb
  storageContainerName: zheng-test-rg-stageartifacts

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Checkout azure-javaee-iaas
        uses: actions/checkout@v2
        with:
          repository: Azure/azure-javaee-iaas
          path: azure-javaee-iaas
          ref: ${{ env.ref_javaee }}  

      - name: Checkout arm-ttk
        uses: actions/checkout@v2
        with:
          repository: Azure/arm-ttk
          path: arm-ttk
          ref: ${{ env.ref_armttk }}
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          path: ${{ env.offerName }}
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Build azure-javaee-iaas
        run: mvn -DskipTests clean install --file azure-javaee-iaas/pom.xml
      - name: Build and test
        run: mvn -Dgit.repo=${{ env.userName }} -Dgit.tag=1.0.1 -DibmUserId=${{ env.ibmUserId }} -DibmUserPwd=${{ env.ibmPassword }} -DvmAdminId=${{ env.vmAdminId }} -DvmAdminPwd=${{ env.vmAdminPassword }} -DdnsLabelPrefix=wsp -Dtest.args="-Test All" -Ptemplate-validation-tests clean install --file ${{ env.offerName }}/pom.xml
      - uses: azure/login@v1
        id: azure-login
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      # - uses: azure/CLI@v1
      #   with:
      #     azcliversion: ${{ env.azCliVersion }}
      #     inlineScript: |
      #       az storage blob download \
      #       --container-name ${{ env.storageContainerName }} \
      #       --file ${{ env.offerName }}/target/arm/agent.installer.linux.gtk.x86_64_1.9.0.20190715_0328.zip \
      #       --name agent.installer.linux.gtk.x86_64_1.9.0.20190715_0328.zip \
      #       --account-key ${{ secrets.STORAGE_ACCOUNT_KEY }} \
      #       --account-name ${{ env.storageAccountName }} 
      - name: Run deployment script
        run: |
          cd ${{ env.offerName }}/target/arm

          #Get a 4-hour SAS Token for the artifacts container. Fall back to OSX date syntax if Linux syntax fails.
          plusFourHoursUtc=$(date -u -v+4H +%Y-%m-%dT%H:%MZ 2>/dev/null)  || plusFourHoursUtc=$(date -u --date "$dte 4 hour" +%Y-%m-%dT%H:%MZ)

          #Generate SAS token
          sasToken=$( az storage container generate-sas -n ${{ env.storageContainerName }} --permissions r --expiry "$plusFourHoursUtc" --account-name ${{ env.storageAccountName }} --account-key ${{ secrets.STORAGE_ACCOUNT_KEY }} -o json | sed 's/"//g')
          blobEndpoint=$( az storage account show -n ${{ env.storageAccountName }} -g ${{ env.storagteResourceGroup }} -o json | jq -r '.primaryEndpoints.blob' )
          installKitUri=${{ env.storageContainerName }}/agent.installer.linux.gtk.x86_64_1.9.0.20190715_0328.zip?$sasToken

          #parameters JSON
          parametersJson=$( cat ./parameters.json | jq '.parameters' )
          parametersJson=$( echo "$parametersJson" | jq --arg uri "$installKitUri" '{"installKitUri": {"value":$uri}} + .' )
          parametersJson=$( echo "$parametersJson" | jq -c '.' )

          #Start deployment
          echo "Starting deployment..."
          (
            az deployment group create --name ${{ github.run_id }}${{ github.run_number }} --resource-group ${{ env.storagteResourceGroup }} \
              --template-file ./mainTemplate.json --parameters "$parametersJson"
          )

          if [[ $? -eq 0 ]]; then
            echo "Template has been successfully deployed"
          fi